[2017-12-14 09:42:05] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:42:06] 127.0.0.1 GET http /robots.txt? 404 NOT FOUND
[2017-12-14 09:42:24] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:50:26] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:50:53] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    print(kb_file)
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:52:45] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 91, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:54:12] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 91, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:54:53] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 91, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:55:25] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:55:42] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
    if "kb_snapshot" in self.__config:
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:55:49] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 91, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:56:10] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 121, in entity_linking
    el = EL(config, __entity, __elastic, __fcache)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 91, in __init__
    load_kb_snapshot(self.__config["kb_snapshot"])
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
    with open(kb_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/snapshot_2015_10.txt'

[2017-12-14 09:57:48] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 122, in entity_linking
    res = el.link(query)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 132, in link
    linker = self.__get_linker(q)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 119, in __get_linker
    self.__model = pickle.load(open(self.__config["model_file"], "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/model.txt'

[2017-12-14 09:58:13] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 122, in entity_linking
    res = el.link(query)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 132, in link
    q = Query(query, qid)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 119, in __get_linker
    if self.__model is None:
FileNotFoundError: [Errno 2] No such file or directory: 'data/el/model.txt'

[2017-12-14 09:58:22] 127.0.0.1 GET http /el?q=sea 200 OK
[2017-12-18 11:11:54] 127.0.0.1 GET http /er?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 109, in retrieval
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/er.py", line 111, in retrieve
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/er.py", line 106, in __get_scorer
  File "/Users/arashdn/Desktop/nordlys/nordlys/core/retrieval/scorer.py", line 53, in get_scorer
  File "/Users/arashdn/Desktop/nordlys/nordlys/core/retrieval/scorer.py", line 75, in __init__
  File "/Users/arashdn/Desktop/nordlys/nordlys/core/retrieval/scorer.py", line 30, in __init__
  File "/Users/arashdn/Desktop/nordlys/nordlys/core/retrieval/elastic.py", line 116, in analyze_query
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
TypeError: analyze() got an unexpected keyword argument 'analyzer'

[2017-12-18 11:11:54] 127.0.0.1 GET http /robots.txt? 404 NOT FOUND
[2017-12-18 11:11:58] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 123, in entity_linking
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
FileNotFoundError: [Errno 2] No such file or directory: '/Users/arashdn/Desktop/nordlys/data/el/snapshot_2015_10.txt'

[2017-12-18 11:12:01] 127.0.0.1 GET http /el?q=sea 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/api.py", line 123, in entity_linking
  File "/Users/arashdn/Desktop/nordlys/nordlys/services/el.py", line 90, in __init__
  File "/Users/arashdn/Desktop/nordlys/nordlys/logic/el/el_utils.py", line 18, in load_kb_snapshot
FileNotFoundError: [Errno 2] No such file or directory: '/Users/arashdn/Desktop/nordlys/data/el/snapshot_2015_10.txt'

[2017-12-18 11:12:04] 127.0.0.1 GET http /? 200 OK
